### ISSUE TITLE
Is the source code release mentioned on the github.io page still on the way?

### ISSUE THREAD

**Issue by Iamgoofball** [liusongxiang/BNE-Seq2SeqMoL-VC#3]
I wanted to follow up on this as this looks extremely cool and I'd like to train some models using it.

**Comment by liusongxiang** [comment]
Hi, the paper is still under review. The codes will be released once accepted. 
Thank you for your attention.

**Comment by Iamgoofball** [comment]
Cool, I hope the review process goes well! Good luck! :)

**Comment by Iamgoofball** [comment]
Yo, how's it going? Has your paper gotten accepted yet?

**Comment by liusongxiang** [comment]
@Iamgoofball 
Hi, sorry for the late reply.
I am open-sourcing all the codes in the repo of https://github.com/liusongxiang/ppg-vc
Thanks.

**Comment by Iamgoofball** [comment]
Thanks, excited to give this a try with my datasets!
